### PR TITLE
Integrating Enhanced System Tray & Added Movestack and Winicon patches

### PR DESCRIPTION
**Pull request by fesowowako**
I've refined the system tray functionality and seamlessly incorporated the MoveStack patch. This enhancement grants the flexibility to rearrange clients within the stack and interchange them with the master client. Additionally, I've integrated the Winicon patch, allowing users to toggle its presence via config.h and customise the icon size according to preference. The Winicon patch relies on Imlib2 for icon scaling, so ensure you install that package according to your distribution. Lastly, I've updated the Swallow patch to ensure optimal performance and usability.

### CODE REVIEW

**Comment by fesowowako** [comment]
@ChrisTitusTech Could you kindly inform me whether you intend to employ either slstatus or dwmblocks as your status bar? This information will enable me to evaluate the feasibility of eliminating redundant code from my upcoming commit.

**Comment by ChrisTitusTech** [comment]
@fesowowako I'd switch to whichever you prefer. I've loved all your PR's as it has simplified a lot of my DWM. 

Right now I'm using slstatus, but I understand it isn't the prettiest looking thing out there.

**Comment by fesowowako** [comment]
@ChrisTitusTech I personally favour slstatus due to its simplicity and seamless functionality, though it ultimately comes down to personal preference. I'm considering integrating the Status2D patch into dwm to enable colour support and rectangle drawing within the dwm status bar, should aesthetics be a priority for you.

**Comment by ChrisTitusTech** [comment]
@fesowowako sounds great to me, integrating slstatus sounds amazing.

**Pull request merged**
