### PR TITLE
Individual Fake Fullscreen for Clients + Enhanced Resizecorners Feature + Hide vacant Tags Patch

### PR DESCRIPTION
**Pull request by fesowowako**
The fake fullscreen client was introduced because I spotted you'd tried it out before but dropped it when you couldn't get it to work properly in a regular fullscreen mode. It's a bit like the fake fullscreen feature we had, where it lets clients go into a fullscreen mode but keeps them within their designated area. What sets this one apart is that you can switch on fake fullscreen for each client individually, instead of having it apply to everything at once.

### CODE REVIEW

**Comment by iljo-dp** [comment]
as a long time dwm user, this is a great feature imo, haven't tried this pull request's code, but fakefullscreen is neat <3

**Comment by fesowowako** [comment]
For those interested in the last four commits, they encompass minor adjustments and the implementation of a feature akin to resizecorners, albeit with a unique twist: the cursor retains its original shape rather than morphing into corners. This enhancement supersedes the existing resizecorners functionality, promising a significantly improved user experience.

**Comment by ChrisTitusTech** [comment]
These adjustments are amazing. I'm curious what are you using for status? slstatus dwmblocks or something else. I need to tackle this next.

**Comment by fesowowako** [comment]
Well, actually, I prefer Slstatus as it's really powerful and sufficient for my needs.

**Pull request merged**
