### PR TITLE
feh fix

### PR DESCRIPTION
**Pull request by MGRAFF2006**
Setup.sh checks for the background directory being existent

if not cloning nord-backgrounds to have any

changing config.h to support users not named titus

### CODE REVIEW

**Review by AkkhilCodingHub — CHANGES_REQUESTED** [review]
Brother your thoughts are right just one thing if dir doesn't exist create it

**Comment by MGRAFF2006** [comment]
Was not sure how much you should screw with someones files, that is why i returned instead of changing it, thank you for the feedback. I'm am new regarding GitHub, and figured these were things i recognized and could figure out.

**Comment by AkkhilCodingHub** [comment]
Don't worry if @ChrisTitusTech  doesn't like it he will just state a comment or request update

**Comment by MGRAFF2006** [comment]
@AkkhilCodingHub I am not using Linux for as long, and was in and out of it for some time. I am pretty sure that the dependency installation section could need a  extension as the feh packege required / used in dwm is not mentioned. I could add it, but wouldn't like to introduce errors because of missing dependencies or something. I feel like this needs to be tackled by someone else another time.

**Review by ChrisTitusTech — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
