### PR TITLE
[slstatus] A Quick Fix

### PR DESCRIPTION
**Pull request by RazoBeckett**
Added a Quick function to fix the slstatus issue present on linutil: [#351](https://github.com/ChrisTitusTech/linutil/issues/351).

Sorry for not following the description layout this doesn't have much, anybody can understand.

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
This setup script has been moved to Linutil.

**Comment by RazoBeckett** [comment]
@nnyyxxxx 
oh why it's still here then ? 🤔

**Review by AkkhilCodingHub — COMMENTED** [review]
Make like a prompt for the user if they want to use slstatus

**Comment by nnyyxxxx** [comment]
> Make like a prompt for the user if they want to use slstatus

This script has been moved to Linutil, please make a PR over there.

**Comment by nnyyxxxx** [comment]
@RazoBeckett Please close this, and make one over at the Linutil repository.

**Comment by nnyyxxxx** [comment]
> Make like a prompt for the user if they want to use slstatus

This script has been moved to Linutil.

**Comment by RazoBeckett** [comment]
> > Make like a prompt for the user if they want to use slstatus
> 
> This script has been moved to Linutil.

working on it.
Once i create PR i will close this one.

**Comment by RazoBeckett** [comment]
@nnyyxxxx i have created PR: [#392](https://github.com/ChrisTitusTech/linutil/pull/392) on linutil please check tell me so i can close this one.

**Comment by nnyyxxxx** [comment]
> @nnyyxxxx i have created PR: [#392](https://github.com/ChrisTitusTech/linutil/pull/392) on linutil please check tell me so i can close this one.

Looks ok at first glance, you can close this one now.

**Comment by RazoBeckett** [comment]
@nnyyxxxx closing.

**Pull request closed without merging**
