### PR TITLE
Migrate Alacritty config from TOML to YAML format

### PR DESCRIPTION
**Pull request by RazoBeckett**
# Pull Request

## Title
Migrate Alacritty config from TOML to YAML format

## Type of Change
- [x] New feature
- [x] Refactoring
- [x] Hotfix

## Description
Converted Alacritty config back to YAML format for compatibility with systems using older Alacritty versions

## Additional Information:
Merge this [#367](https://github.com/ChrisTitusTech/linutil/pull/367) first on Linutil.

## Issue related to PR
resolves the issue: [#364](https://github.com/ChrisTitusTech/linutil/issues/364) on linutil.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by mashrukk** [comment]
@RazoBeckett Alacritty prefers toml over yaml file format. With a yml version of my toml file, this shows in the terminal.

image

**Comment by RazoBeckett** [comment]
@mashrukk ya i know it after it does convert it to toml using the `alacritty migrate` command. check the PR [#367](https://github.com/ChrisTitusTech/linutil/pull/367)

**Comment by mashrukk** [comment]
@RazoBeckett Oh right, that makes sense.

**Comment by RazoBeckett** [comment]
> @RazoBeckett Oh right, that makes sense. He has to merge both PRs otherwise this won't work

YES same thing is mentioned in the Description body of both PRs i hope he reads and then merge or take action on PR.

**Comment by ChrisTitusTech** [comment]
Ahhh let those old men suffer.... TOML FOR LIFE... YAML is for LOSERS!

**Pull request closed without merging**
